import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {once} from 'node:events';

test('API validates folder, saves and compares real parsed evidence, rejects duplicates and cross-origin writes',async()=>{
 const temp=await mkdtemp(path.join(os.tmpdir(),'sto-parser-test-'));
 const proc=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'0',STO_DATA_DIR:path.join(temp,'data')},stdio:['ignore','pipe','pipe']});
 try {
  let buffer='';const base=await new Promise((resolve,reject)=>{proc.stdout.on('data',d=>{buffer+=d;const m=/http:\/\/127\.0\.0\.1:\d+/.exec(buffer);if(m)resolve(m[0]);});proc.on('error',reject);proc.on('exit',code=>reject(new Error(`Server exited ${code}`)));});
  const html=await (await fetch(base)).text(); const token=/name="sto-token" content="([^"]+)"/.exec(html)[1];
  const headers={'X-STO-Token':token,'Content-Type':'application/json'};
  const post=async(route,b)=>{const response=await fetch(base+'/api/'+route,{method:'POST',headers,body:JSON.stringify(b)});return {status:response.status,value:await response.json()};};
  assert.equal((await fetch(base+'/api/state')).status,400);
  assert.equal((await fetch(base+'/api/build',{method:'POST',headers:{...headers,Origin:'https://example.com'},body:'{}'})).status,400);
  assert.equal((await post('folder',{folder:temp})).status,400);
  const log='26:09:07:08:00:00.0::Captain,P[1@2 Captain@account],,*,Enemy,C[2 Enemy],Beam,Pn.1,Phaser,,100,110\n26:09:07:08:00:10.0::Captain,P[1@2 Captain@account],,*,Enemy,C[2 Enemy],Beam,Pn.1,Phaser,,200,220\n';
  await writeFile(path.join(temp,'combatlog_test.log'),log+'26:09:07:08:02:10.0::Captain,P[1@2 Captain@account],,*,Enemy,C[2 Enemy],Beam,Pn.1,Phaser,,300,330\n');
  assert.equal((await post('folder',{folder:temp})).status,200);
  assert.equal((await post('analyze',{name:'../secret.log'})).status,400);
  const analyzed=(await post('analyze',{name:'combatlog_test.log'})).value;
  assert.equal(analyzed.encounters[0].players[0].dps,30);
  assert.equal(analyzed.encounters.length,2);
  assert.equal(analyzed.fullLog.players[0].total,600);
  assert.equal(analyzed.fullLog.duration,130);
  assert.equal(analyzed.fullLog.players[0].dps,600/130);
  assert.deepEqual(analyzed.fullLog.encounterIds,analyzed.encounters.map(e=>e.id));
  const a=(await post('build',{name:'Baseline',ship:'Test ship'})).value;
  const b=(await post('build',{name:'Candidate',ship:'Test ship'})).value;
  const input={buildId:a.id,encounterId:analyzed.encounters[0].id,playerId:'P[1@2 Captain@account]',patrolId:'strike-at-seedea',difficulty:'Advanced',party:'Solo',spaceConfirmed:true};
  assert.equal((await post('run',{...input,spaceConfirmed:false})).status,400);
  assert.equal((await post('run',{...input,patrolId:'ground'})).status,400);
  assert.equal((await post('run',input)).status,200);
  assert.equal((await post('run',{...input,buildId:b.id})).status,400);
  assert.equal((await post('run',{...input,encounterId:analyzed.fullLog.id})).status,400);
  const comparison=(await post('compare',{baseline:a.id,candidate:b.id,playerId:input.playerId,...input})).value;
  assert.equal(comparison.baseline.count,1);assert.equal(comparison.candidate.count,0);
  assert.match(comparison.message,/No matching confirmed runs/);
  const saved=(await (await fetch(base+'/api/state',{headers})).json());
  assert.equal(saved.profiles.length,1);assert.equal(saved.loadouts.length,1);
  assert.equal((await post('run/edit',{id:saved.runs[0].id,buildId:b.id,patrolId:'wanted',difficulty:'Elite',party:'Group',spaceConfirmed:true})).status,200);
  const edited=await(await fetch(base+'/api/state',{headers})).json();
  assert.equal(edited.runs[0].patrolId,'wanted');assert.equal(edited.runs[0].buildId,b.id);
  assert.equal((await post('run/edit',{id:saved.runs[0].id,buildId:'missing',context:'Invalid'})).status,400);
  const persisted=JSON.parse(await readFile(path.join(temp,'data','state.json'),'utf8'));assert.equal(persisted.runs.length,1);assert.equal(persisted.builds.length,2);
 } finally {proc.kill();await once(proc,'exit').catch(()=>{});await rm(temp,{recursive:true,force:true});}
});
