const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=[{id:'franklin',name:'USS Franklin',loadouts:[{id:'beams',name:'Beam Broadside',variations:[{id:'xv',name:'XV',notes:'Unchanged beam setup. These two flights used the same equipment.',weapons:'Phaser beam arrays · fore torpedo',consoles:'Phaser damage consoles · hull repair console',runs:[{id:'r1',date:'Sep 11 · 14:08',map:'Strike at Seedea',difficulty:'Elite',party:'Solo',duration:222,dps:35094,pets:22753,taken:4280},{id:'r2',date:'Sep 11 · 16:20',map:'Strike at Seedea',difficulty:'Elite',party:'Solo',duration:220,dps:36245,pets:23240,taken:4010}]},{id:'beam2',name:'Elite Valkyrie test',notes:'One Elite + one Advanced hangar. Copied from XV, then changed the hangar notes.',weapons:'Phaser beam arrays · fore torpedo',consoles:'Phaser damage consoles · hull repair console',runs:[]},{id:'beam3',name:'Console swap',notes:'Testing a different damage console.',weapons:'Phaser beam arrays · fore torpedo',consoles:'Alternate damage console',runs:[]}]},{id:'torps',name:'Torpedo Specialist',variations:[{id:'torp1',name:'Baseline',notes:'Initial torpedo setup.',weapons:'Torpedoes',consoles:'Projectile damage consoles',runs:[]},{id:'torp2',name:'Forward weapon test',notes:'One forward weapon changed.',weapons:'Alternate fore torpedo',consoles:'Projectile damage consoles',runs:[]},{id:'torp3',name:'Survival test',notes:'Testing a repair console.',weapons:'Torpedoes',consoles:'Projectile consoles + repair console',runs:[]}]}]},{id:'archer',name:'USS Archer',loadouts:[{id:'cannons',name:'Cannon Escort',variations:[{id:'cannon1',name:'Baseline',notes:'Initial escort setup.',weapons:'Dual cannons · rear turrets',consoles:'Energy damage consoles',runs:[]},{id:'cannon2',name:'Turret swap',notes:'Testing a different rear turret.',weapons:'Dual cannons · alternate turret',consoles:'Energy damage consoles',runs:[]}]}]}];
initial[0].loadouts[0].variations[1].runs.push({id:'valkyrie-r1',date:'Sep 11 · 18:10',map:'Strike at Seedea',difficulty:'Elite',party:'Solo',duration:224,dps:37480,pets:24510,taken:4150});
let ships,shipId,loadoutId,variationId,archived=false;const number=n=>n.toLocaleString('en-US');
function context(){const ship=ships.find(s=>s.id===shipId);const loadout=ship?.loadouts.find(l=>l.id===loadoutId);return {ship,loadout,variation:loadout?.variations.find(v=>v.id===variationId)};}
function message(t){$('notice').textContent=t;}
function reset(){ships=structuredClone(initial);shipId='franklin';loadoutId=null;variationId=null;archived=false;$('ship-select').innerHTML=ships.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');render();}
function render(){const {ship,loadout,variation}=context();$('ship-select').value=shipId;$('archive-toggle').classList.toggle('active',archived);$('shipyard').classList.toggle('active',!archived);let html='';
 if(archived){html='<h1>Archived variations</h1><p>Archived setups retain their runs. Restore one to put it back in the active list.</p>';for(const s of ships)for(const l of s.loadouts)for(const v of l.variations.filter(v=>v.archived))html+=`<article class="panel"><h2>${esc(v.name)}</h2><p>${esc(s.name)} / ${esc(l.name)} · ${v.runs.length} saved runs</p><button data-restore="${v.id}">Restore variation</button></article>`;if(!ships.some(s=>s.loadouts.some(l=>l.variations.some(v=>v.archived))))html+='<p>No archived variations. Open a variation to archive it.</p>';}
 else if(!loadout){html=`<h1>${esc(ship.name)}</h1><p>Choose a loadout. A variation is one equipment setup; repeated flights stay inside it.</p><div class="preview-grid">${ship.loadouts.map(l=>`<article class="panel"><h2>${esc(l.name)}</h2><p>${l.variations.filter(v=>!v.archived).length} active variations · ${l.variations.reduce((n,v)=>n+v.runs.length,0)} saved runs</p><button data-loadout="${l.id}">Open loadout →</button></article>`).join('')}</div><div class="panel"><h2>Your ships</h2><div class="actions">${ships.map(s=>`<button data-ship="${s.id}">${esc(s.name)}</button>`).join('')}</div></div>`;}
 else if(!variation){html=`<button data-back="ship">← Ship profile</button><p class="crumbs">${esc(ship.name)} / ${esc(loadout.name)}</p><h1>Equipment variations</h1><p>Open a setup to add flights or review its run history. You do not need a new variation for another patrol.</p><div class="preview-grid">${loadout.variations.filter(v=>!v.archived).map(v=>`<article class="panel"><h2>${esc(v.name)}</h2><p>${esc(v.notes)}</p><p>${v.runs.length} saved runs</p><button data-variation="${v.id}">Open setup & runs →</button></article>`).join('')||'<p>All variations in this loadout are archived.</p>'}</div>`;}
 else {html=`<button data-back="loadout">← All variations</button><p class="crumbs">${esc(ship.name)} / ${esc(loadout.name)} / ${esc(variation.name)}</p><h1>${esc(variation.name)}</h1><span class="tag">ONE EQUIPMENT SETUP · ${variation.runs.length} SAVED RUNS</span><details id="run-history"><summary>Run history (${variation.runs.length}) <small>Expand to review or compare flights</small></summary><p class="run-help">Select two runs to compare consistency with unchanged equipment. Conditions must match.</p><div class="table-wrap"><table><thead><tr><th>SELECT</th><th>DATE</th><th>PATROL</th><th>DIFFICULTY</th><th>PARTY</th><th>DPS</th></tr></thead><tbody>${variation.runs.map(r=>`<tr><td><input type="checkbox" data-run="${r.id}" aria-label="Select run ${esc(r.date)}"></td><td>${r.date}</td><td>${r.map}</td><td>${r.difficulty}</td><td>${r.party}</td><td>${number(r.dps)}</td></tr>`).join('')||'<tr><td colspan="6">No runs yet. Add a run to this setup.</td></tr>'}</tbody></table></div><div class="actions"><button id="compare-runs" disabled>Compare selected runs</button></div><div id="comparison"></div></details><div class="actions"><button class="primary" id="add-run">Add run to ${esc(variation.name)}</button><button class="quiet" id="copy-variation">Create variation from this setup</button><button class="quiet" id="archive">Archive variation</button></div><div class="panel"><h2>Equipment & notes</h2><p>${esc(variation.notes)}</p><div class="equipped"><div><h3>Weapons</h3><p>${esc(variation.weapons)}</p></div><div><h3>Consoles</h3><p>${esc(variation.consoles)}</p></div></div><p class="muted">Illustrative manual notes, not detected equipment. A future equipment editor could live here.</p></div>`;}
 $('content').innerHTML=html;
 if(loadout&&!variation&&!archived){
  const variations=loadout.variations.filter(v=>!v.archived);
  const choices=variations.map(v=>`<option value="${esc(v.id)}">${esc(v.name)} · ${v.runs.length} runs</option>`).join('');
  const panel=document.createElement('section');panel.className='panel variation-comparison';
  panel.innerHTML=`<h2>Compare variations</h2><p>Compare equipment setups using their matching saved runs. To compare two flights of the same setup, open its Run history instead.</p><div class="preview-grid"><label>Baseline<select id="compare-baseline">${choices}</select></label><label>Candidate<select id="compare-candidate">${choices}</select></label></div><label>Matching patrol / difficulty / party<select id="compare-condition"></select></label><div class="actions"><button id="compare-setups" class="primary">Compare variations →</button></div><div id="setup-result" role="status"></div>`;
  $('content').insertBefore(panel,$('content').querySelector('.preview-grid'));
  if(variations.length>1)$('compare-candidate').value=variations[1].id;
  const key=r=>JSON.stringify([r.map,r.difficulty,r.party]);
  function updateConditions(){
   const a=variations.find(v=>v.id===$('compare-baseline').value),b=variations.find(v=>v.id===$('compare-candidate').value);
   const common=[...new Set((a?.runs||[]).map(key))].filter(k=>b?.runs.some(r=>key(r)===k));
   $('compare-condition').innerHTML=common.map(k=>`<option value="${esc(k)}">${esc(JSON.parse(k).join(' / '))}</option>`).join('')||'<option value="">No matching saved runs</option>';
   $('compare-setups').disabled=!common.length||a===b;
   $('setup-result').textContent=a===b?'Choose two different variations.':!common.length?'Both variations need a saved run under the same conditions.':'';
  }
  $('compare-baseline').onchange=$('compare-candidate').onchange=updateConditions;
  $('compare-condition').onchange=()=>{$('setup-result').replaceChildren();};
  $('compare-setups').onclick=()=>{
   const a=variations.find(v=>v.id===$('compare-baseline').value),b=variations.find(v=>v.id===$('compare-candidate').value),condition=$('compare-condition').value;
   const ar=a.runs.filter(r=>key(r)===condition),br=b.runs.filter(r=>key(r)===condition);if(!ar.length||!br.length||a===b)return;
   const avg=(runs,get)=>runs.reduce((sum,r)=>sum+get(r),0)/runs.length;
   const metrics=[['Total DPS (includes pets)',r=>r.dps],['Ship DPS',r=>r.dps-r.pets],['Pet DPS',r=>r.pets],['Damage taken / second',r=>r.taken],['Duration (seconds)',r=>r.duration]];
   const delta=(avg(br,r=>r.dps)/avg(ar,r=>r.dps)-1)*100;
   $('setup-result').innerHTML=`<div class="compare-result"><h2>${esc(a.name)} vs. ${esc(b.name)}</h2><p>${esc(JSON.parse(condition).join(' / '))}</p><p><strong>${delta>=0?'+':''}${delta.toFixed(1)}% observed mean DPS difference</strong></p><div class="table-wrap"><table><thead><tr><th>METRIC</th><th>${esc(a.name)} (${ar.length} runs)</th><th>${esc(b.name)} (${br.length} runs)</th><th>CHANGE</th></tr></thead><tbody>${metrics.map(([label,get])=>{const x=avg(ar,get),y=avg(br,get);return `<tr><td>${label}</td><td>${number(Math.round(x))}</td><td>${number(Math.round(y))}</td><td>${y-x>=0?'+':''}${number(Math.round(y-x))}</td></tr>`;}).join('')}</tbody></table></div><p>Each matching run has equal weight. These are invented preview numbers, not an equipment recommendation. One candidate run is too little evidence to establish an improvement.</p></div>`;
  };updateConditions();
 }
 bind();}
function bind(){$('content').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.ship){shipId=b.dataset.ship;loadoutId=variationId=null;render();}if(b.dataset.loadout){loadoutId=b.dataset.loadout;variationId=null;render();}if(b.dataset.variation){variationId=b.dataset.variation;render();}if(b.dataset.back){variationId=null;if(b.dataset.back==='ship')loadoutId=null;render();}if(b.dataset.restore){for(const s of ships)for(const l of s.loadouts){const v=l.variations.find(v=>v.id===b.dataset.restore);if(v)v.archived=false;}render();message('Variation restored with its runs intact.');}};
 const {variation}=context();if(!variation||archived)return;
 $('add-run').onclick=()=>dialog('Add a run to '+variation.name,'This simulates importing a new flight with the same equipment. It adds a sample run, not a variation.','Run note','Another unchanged flight',value=>{variation.runs.push({id:crypto.randomUUID(),date:'New sample · '+value,map:'Strike at Seedea',difficulty:'Elite',party:'Solo',duration:225,dps:35700,pets:23000,taken:4100});render();$('run-history').open=true;message('Sample run added to '+variation.name+'. The equipment variation is unchanged.');});
 $('copy-variation').onclick=()=>dialog('Create variation from this setup','Equipment notes will be copied. Saved runs stay with the original setup.','New variation name','',name=>{const {loadout}=context();if(loadout.variations.some(v=>v.name.toLowerCase()===name.toLowerCase()))throw Error('Choose a different variation name.');const v={...structuredClone(variation),id:crypto.randomUUID(),name,runs:[],archived:false};loadout.variations.push(v);variationId=v.id;render();message('New variation created with copied notes and no runs.');});
 $('archive').onclick=()=>{variation.archived=true;variationId=null;render();message('Variation archived. Its saved runs are retained; use Archived variations to restore it.');};
 $('run-history').onchange=()=>{$('compare-runs').disabled=document.querySelectorAll('[data-run]:checked').length!==2;};
 $('compare-runs').onclick=()=>{const selected=[...document.querySelectorAll('[data-run]:checked')].map(el=>variation.runs.find(r=>r.id===el.dataset.run));const [a,b]=selected;if(!b)return;const delta=((b.dps/a.dps)-1)*100;$('comparison').innerHTML=`<div class="compare-result"><h2>Same setup · two flights</h2><p>${esc(a.map)} / ${a.difficulty} / ${a.party}</p><div class="run-metrics"><div>First selected run<br><strong>${number(a.dps)} DPS</strong></div><div>Second selected run<br><strong>${number(b.dps)} DPS</strong></div><div>Observed difference<br><strong>${delta>=0?'+':''}${delta.toFixed(1)}%</strong></div></div><p>Equipment stayed the same. This shows run-to-run variation, not an equipment improvement.</p><div class="table-wrap"><table><tr><th>METRIC</th><th>FIRST RUN</th><th>SECOND RUN</th></tr><tr><td>Duration</td><td>${a.duration}s</td><td>${b.duration}s</td></tr><tr><td>Pet DPS (included in total)</td><td>${number(a.pets)}</td><td>${number(b.pets)}</td></tr><tr><td>Damage taken / second</td><td>${number(a.taken)}</td><td>${number(b.taken)}</td></tr></table></div></div>`;};}
function dialog(title,help,label,value,save){const d=document.createElement('dialog');d.innerHTML=`<form><h2>${esc(title)}</h2><p>${esc(help)}</p><label>${esc(label)}<input required maxlength="80" value="${esc(value)}"></label><p role="alert"></p><div class="actions"><button type="submit" class="primary">Continue</button><button type="button">Cancel</button></div></form>`;document.body.append(d);d.querySelector('[type=button]').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=e=>{e.preventDefault();const name=d.querySelector('input').value.trim();if(!name)return;try{save(name);d.close();}catch(error){d.querySelector('[role=alert]').textContent=error.message;}};d.showModal();}
 $('ship-select').onchange=()=>{shipId=$('ship-select').value;loadoutId=variationId=null;archived=false;render();};$('shipyard').onclick=()=>{loadoutId=variationId=null;archived=false;render();};$('archive-toggle').onclick=()=>{archived=true;render();};$('reset').onclick=()=>{reset();message('Example reset.');};reset();
